system:
  loop_interval_seconds: 30
  log_level: "INFO"
  redis_host: "localhost"
  redis_port: 6379
  seed: 1337

data_source:
  exchanges: ["coinbase", "kraken"]

# v4.7.5 data-plane
harvester:
  core_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","AVAX_USD_SPOT","LINK_USD_SPOT",
                 "ADA_USD_SPOT","XRP_USD_SPOT","DOGE_USD_SPOT","MATIC_USD_SPOT","DOT_USD_SPOT","EUR_USD_SPOT",
                 "LTC_USD_SPOT","LDO_USD_SPOT","BCH_USD_SPOT","UNI_USD_SPOT","ATOM_USD_SPOT","FIL_USD_SPOT",
                 "NEAR_USD_SPOT","ARB_USD_SPOT","OP_USD_SPOT","INJ_USD_SPOT","APT_USD_SPOT","XLM_USD_SPOT",
                 "ALGO_USD_SPOT","SUI_USD_SPOT","SHIB_USD_SPOT"]
  dynamic_enabled: true
  timeframes_by_lane:
    core:     ["1m","5m","15m","1h","4h","1d"]
    moonshot: ["1m","5m","15m"]
    eil:      "on_demand"
  quotas:
    coinbase: { max_requests_per_min: 60, min_sleep_ms: 200 }
    kraken:   { max_requests_per_min: 45, min_sleep_ms: 250 }
  bootstrap_days_default:
    "1m": 7
    "5m": 14
    "15m": 30
    "1h": 365
    "4h": 730
    "1d": 1825
  retention_days:
    "1m": 90
    "5m": 90
    "15m": 365
    "1h": 1825
    "4h": 1825
    "1d": 3650
  max_gap_pct_accept: 0.50  # will tighten after staged backfill completes
  bootstrap_days_override: {"1m": 1, "5m": 3}
  staged_backfill:
    enabled: true
    targets_days:
      "1m": [1, 3, 7]
      "5m": [3, 14, 30]
      "15m": [7, 30, 90]

screener:
  snapshot_dir: "data/screener_snapshots"
  min_24h_volume_usd: 10000000
  min_price: 0.20
  max_markets: 24
  typical_order_usd: 200
  max_spread_bps: 25
  max_impact_bps: 60
  stablecoin_parity_warn_bps: 100
  derivatives_enabled: false
  sentiment_weight: 0.0

feeds:
  cryptopanic: { enabled: false, window_hours: 6, min_score: -1.0 }
  onchain:     { enabled: true, min_notional_eth: 100.0 }
  orderflow:   { enabled: true, top_levels: 5 }

validation:
  dsr:
    enabled: false  # TEMP bootstrap: disabled to allow faster initial promotions; revert to true after seeding
    min_prob: 0.60       # require >=60% probability Sharpe not luck (deflated)
    benchmark_sr: 0.0

discovery:
  population_size: 160
  generations_per_cycle: 2
  panel_symbols: 5
  cv_folds: 4
  cv_embargo_bars: 2
  fdr_alpha: 0.10
  cv_method: "kfold"        # Cross-validation method ("kfold" default, or "cpcv" for combinatorial purged CV)
  max_promotions_per_cycle: 3
  max_promotions_per_day: 12     # promotion-debt guard
  promotion_buffer_multiplier: 1.0  # set >1.0 (e.g., 1.10) for tighter buffer
  enable_pruning: true
  promotion_criteria:
    min_trades: 40   # TEMP bootstrap (was 75) -> revert after initial active alpha set
    min_sortino: 1.00  # TEMP bootstrap (was 1.25)
    max_mdd: 0.20
    min_sharpe: 0.90  # TEMP bootstrap (was 1.10)
    min_win_rate: 0.50  # slightly relaxed (was 0.52)
  factor_correlation_max: 0.80   # factor-aware penalty cut-off

prober:
  enabled: true
  perturbations: 64
  delta_fraction: 0.15
  min_robust_score: 0.55

lanes:
  core:     { base_fraction: 0.95, min_fraction: 0.85, max_fraction: 0.99 }
  moonshot: { base_fraction: 0.05, min_fraction: 0.01, max_fraction: 0.20 }

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

risk:
  daily_stop_pct: 0.10
  equity_floor_pct: 0.50
  max_symbol_weight: 0.35
  max_gross_weight: 1.00
  max_order_notional_usd: 150
  max_consecutive_errors: 3
  phases:
    "1000":   { kelly_fraction: 0.6, max_order_notional_usd: 500 }
    "10000":  { kelly_fraction: 0.7, max_order_notional_usd: 1000 }
    "100000": { kelly_fraction: 0.8, max_order_notional_usd: 5000 }
  conserve_mode:
    dd_trigger_pct: 0.15
    gross_weight_scalar: 0.5
    kelly_scalar: 0.6

execution:
  primary_exchange: "coinbase"
  mode: "paper"
  paper_fees_bps: 18
  paper_slippage_bps: 5

llm:
  provider: "openai"
  enable: true
  max_suggestions_per_cycle: 3

eil:
  enabled: true
  fast_window_days: 45
  max_parallel_jobs: 8
  max_queue: 5000
  survivor_top_k: 25

adaptive:
  enabled: true
  stop_vol_window_bars: 24
  daily_stop_pct_floor: 0.05
  daily_stop_pct_ceiling: 0.20
  screener_max_markets_min: 12
  screener_max_markets_max: 36
  population_size_min: 120
  population_size_max: 240

registry:
  allowed_quotes_global: ["USD","USDT","USDC","DAI","FDUSD","TUSD","PYUSD","EUR","GBP"]
  allowed_quotes_by_venue:
    kraken: ["USD","USDT","USDC","EUR"]
    coinbase: ["USD","USDC"]
  base_aliases:
    BTC: ["XBT"]
    IOTA: ["MIOTA"]
  cache_ttl_s: 600
  catalog_refresh_seconds: 900
  timeframe_aliases_by_venue:
    coinbase:
      "4h": "6h"
