system:
  loop_interval_seconds: 90
  log_level: "INFO"
  redis_host: "localhost"
  redis_port: 6379
  seed: 1337

data_source:
  exchanges: ["coinbase", "kraken"]

# v4.7.5 data-plane
harvester:
  core_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","AVAX_USD_SPOT","LINK_USD_SPOT",
                 "ADA_USD_SPOT","XRP_USD_SPOT","DOGE_USD_SPOT","MATIC_USD_SPOT","DOT_USD_SPOT"]
  dynamic_enabled: true
  timeframes_by_lane:
    core:     ["1m","5m","15m","1h","4h","1d"]
    moonshot: ["1m","5m","15m"]
    eil:      "on_demand"
  quotas:
    coinbase: { max_requests_per_min: 60, min_sleep_ms: 200 }
    kraken:   { max_requests_per_min: 45, min_sleep_ms: 250 }
  bootstrap_days_default:
    "1m": 7
    "5m": 14
    "15m": 30
    "1h": 365
    "4h": 730
    "1d": 1825
  retention_days:
    "1m": 90
    "5m": 90
    "15m": 365
    "1h": 1825
    "4h": 1825
    "1d": 3650

screener:
  snapshot_dir: "data/screener_snapshots"
  min_24h_volume_usd: 10000000
  min_price: 0.20
  max_markets: 24
  typical_order_usd: 200
  max_spread_bps: 25
  max_impact_bps: 60
  stablecoin_parity_warn_bps: 100
  derivatives_enabled: false
  sentiment_weight: 0.0

feeds:
  cryptopanic: { enabled: false, window_hours: 6, min_score: -1.0 }
  onchain:     { enabled: false, min_notional_eth: 100.0 }
  orderflow:   { enabled: false, top_levels: 5 }

discovery:
  population_size: 160
  generations_per_cycle: 2
  panel_symbols: 5
  cv_folds: 4
  cv_embargo_bars: 2
  fdr_alpha: 0.10
  max_promotions_per_cycle: 3
  max_promotions_per_day: 12     # promotion-debt guard
  promotion_criteria:
    min_trades: 75
    min_sortino: 1.25
    max_mdd: 0.20
    min_sharpe: 1.10
    min_win_rate: 0.52
  factor_correlation_max: 0.80   # factor-aware penalty cut-off

lanes:
  core:     { base_fraction: 0.95, min_fraction: 0.85, max_fraction: 0.99 }
  moonshot: { base_fraction: 0.05, min_fraction: 0.01, max_fraction: 0.20 }

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

risk:
  daily_stop_pct: 0.10
  equity_floor_pct: 0.50
  max_symbol_weight: 0.35
  max_gross_weight: 1.00
  max_order_notional_usd: 150
  max_consecutive_errors: 3
  phases:
    "1000":   { kelly_fraction: 0.6, max_order_notional_usd: 500 }
    "10000":  { kelly_fraction: 0.7, max_order_notional_usd: 1000 }
    "100000": { kelly_fraction: 0.8, max_order_notional_usd: 5000 }
  conserve_mode:
    dd_trigger_pct: 0.15
    gross_weight_scalar: 0.5
    kelly_scalar: 0.6

execution:
  primary_exchange: "coinbase"
  mode: "paper"
  paper_fees_bps: 18
  paper_slippage_bps: 5

llm:
  provider: "openai"
  enable: true
  max_suggestions_per_cycle: 3

eil:
  enabled: true
  fast_window_days: 45
  max_parallel_jobs: 8
  max_queue: 5000
  survivor_top_k: 25

prober:
  enabled: true
  perturbations: 64
  delta_fraction: 0.15
  min_robust_score: 0.55

micro_live:
  enabled: false
  notional_usd: 3.00
  cycle_budget_trades: 5
  venues: ["coinbase", "kraken"]

adaptive:
  enabled: true
  stop_vol_window_bars: 24
  daily_stop_pct_floor: 0.05
  daily_stop_pct_ceiling: 0.20
  screener_max_markets_min: 12
  screener_max_markets_max: 36
  population_size_min: 120
  population_size_max: 240
