system:
  loop_interval_seconds: 30
  log_level: "TRACE"
  redis_host: "localhost"
  redis_port: 6379
  seed: 1337

features:
  zscore_lookback: 200   # rolling window for lagged z-score normalization
  volatility_windows: [5, 10, 20]
  parkinson_vol_windows: [5, 10, 20]
  momentum:
    sma_windows: [5, 10, 20, 50]
    ema_windows: [5, 10, 20, 50]
    roc_windows: [1, 3, 5, 10]

data_source:
  exchanges: ["coinbase", "kraken"]

screener:
  snapshot_dir: "data/screener_snapshots"
  min_24h_volume_usd: 8000000
  min_avg_daily_volume_14d: 5000000
  min_trades_per_day_14d: 100
  max_bid_ask_spread_pct: 0.5
  min_start_date_days_ago: 30
  min_price: 0.20
  max_markets: 200
  typical_order_usd: 200
  max_spread_bps: 25
  max_impact_bps: 60
  stablecoin_parity_warn_bps: 100
  derivatives_enabled: false
  sentiment_weight: 0.0
  exclude_stable_stable: true
  display:
    enabled: false

# v4.7.5 data-plane
harvester:
  core_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","LTC_USD_SPOT","UNI_USD_SPOT","ATOM_USD_SPOT","FIL_USD_SPOT","NEAR_USD_SPOT","ARB_USD_SPOT","OP_USD_SPOT","INJ_USD_SPOT","APT_USD_SPOT","XLM_USD_SPOT","ALGO_USD_SPOT","SUI_USD_SPOT","SHIB_USD_SPOT","LDO_USD_SPOT","BCH_USD_SPOT"]
  restrict_single_symbol: false
  dynamic_enabled: true
  timeframes_by_lane:
    core: ["1m","5m","1h"]       # TEMP: trim to essential tfs
    moonshot: ["1m","5m"]          # TEMP
    eil: ["1m", "5m"]               # FIXED: was "on_demand", expected list
  partial_harvest: true             # CHANGED: re-enable rotation for faster incremental coverage
  aggregate_timeframes:
    enabled: true                   # CHANGED: restore synthetic aggregation (e.g. 5m→1h) for feature depth
    from: "5m"                      # NEW: source timeframe for aggregation
    to: ["1h"]                      # NEW: target timeframes for aggregation
    min_native_rows_threshold: 50   # NEW: skip aggregation if native 1h data has this many rows
    max_tail_hours: 72              # NEW: limit aggregation window to recent data for performance
  min_accept_ratio_for_selection: 0.70 # NEW: min quality for a timeframe to be used by EIL
  checkpoint_reconcile:
    enabled: true                   # CHANGED: forward-only drift correction re-enabled
  bootstrap_mode: "inline"          # TEMP: simplify control path
  min_coverage_for_research: 0.01     # NEW: initial coverage ratio gate for research timeframe
  high_coverage_threshold: 0.80       # NEW: target after first promotion
  priority_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT"]  # NEW: tier A ordering
  panel_target_days: { "1m": 7, "5m": 14, "15m": 30, "1h": 30 }  # NEW: dynamic panel targets (days) for gate derivation
  bootstrap_days_default: { "1m": 2, "5m": 7, "15m": 14, "1h": 45, "4h": 120, "1d": 365 }  # NEW: default historical depth per timeframe (days) used when no checkpoint; aligns with staged_backfill & avoids KeyError
  # NOTE: values are config knobs (no magic); adjust to trade off initial IO vs statistical power.
  # per_exchange_bootstrap optional override structure: { exchange: { timeframe: days } }
  max_flat_fill_bars: 120  # NEW: max synthetic bars to fill for moderate gaps
  limits_by_venue:         # NEW: per-venue fetch overrides
    coinbase:
      ohlcv_limit: 300

feeds:
  cryptopanic: { enabled: true }
  onchain:     { enabled: false, min_notional_eth: 100.0 }
  orderflow:   { enabled: true, top_levels: 5 }

validation:
  min_trades: 6   # TEMP: align validator gate with relaxed stage; restore ≥20 later
  dsr:
    enabled: true
    min_prob: 0.30  # TEMP: loosen to admit probe survivors; restore ≥0.40
    benchmark_sr: 0.0
  sparse_trades:
    enabled: true
    winrate_p_threshold_trades: 25
  bootstrap:
    enabled: true
    n_iter: 500
    min_trades: 10   # TEMP: allow bootstrap on shorter series; restore ≥30
    seed: 1337
    method: basic

discovery:
  promotion_criteria:
    min_trades: 6   # TEMP: allow early probes; restore ≥10 after first survivors
  max_promotions_per_cycle: 1
  max_promotions_per_day: 5
  base_features:
    - "zscore_200"
    - "volatility_5"
    - "volatility_10"
    - "volatility_20"
    - "parkinson_vol_5"
    - "parkinson_vol_10"
    - "parkinson_vol_20"
    - "sma_5"
    - "sma_10"
    - "sma_20"
    - "sma_50"
    - "ema_5"
    - "ema_10"
    - "ema_20"
    - "ema_50"
    # TEMP: reduce churny ROC features during bootstrap
    # - "roc_1"
    # - "roc_3"
    - "roc_5"
    - "roc_10"
  # --- Coverage Gates ---
  # Minimum number of symbols required in panel for statistical validity
  min_panel_symbols: 5  # Increased from 3 for better cross-sectional stability
  
  # Minimum bars per symbol for adequate sample size
  min_bars_per_symbol: 200  # Increased from 100 for robust statistics
  
  # Target panel size for discovery
  panel_symbols: 10  # Increased from 5 for better diversification
  
  # Minimum non-NaN ratio for features to be considered active
  feature_min_non_nan_ratio: 0.30
  
  # Minimum variance threshold for features
  feature_min_variance: 1e-6
  
  max_workers: 8
  population_size: 60    # BOOTSTRAP: cut m to ease BH‑FDR; restore upward after survivors
  generations_per_cycle: 4  # BOOTSTRAP: fewer gens to limit trials per cycle
  cv_folds: 3  # TEMP: bootstrap (reduce CV friction); restore 5
  cv_embargo_bars: 24  # TEMP: bootstrap (shorter embargo); restore 96
  fdr_alpha: 0.50  # TEMP one‑cycle boost; restore ≤0.25 after survivors
  
  # Survivor selection (top-k by score after validation gates)
  survivor_top_k: 25  # Retain more survivors per cycle for breadth
  
  # TEMP: explicit stage ladder for 24h bootstrap; Hyper Lab will auto‑escalate
  gate_stages:
    - name: relaxed
      fdr_alpha: 0.70       # TEMP: one-cycle acceptance boost; revert to ≤0.25 after passes
      dsr_min_prob: 0.25    # TEMP: easier DSR for bootstrap
      min_trades: 5         # TEMP: align with validator for early passes
    - name: baseline
      fdr_alpha: 0.25
      dsr_min_prob: 0.40
      min_trades: 10
    - name: tight
      fdr_alpha: 0.20
      dsr_min_prob: 0.50
      min_trades: 20
  
  gate_stage_escalation:
    survivor_density_min: 0.05
    median_trades_min: 25
    patience_cycles: 3
  factor_correlation_max: 0.80
  enforce_current_gates_on_start: true
  max_return_padding_trim: 5
  max_population_size: 3000
  reseed_fraction: 0.30
  fitness_drawdown_penalty_scale: 0.40
  rejection_sample_size: 8
  rejection_alert_ratio: 0.70
  fitness_concentration_penalty_scale: 0.25
  fitness_variance_penalty_scale: 0.15
  fitness_activation_scale: 20
  pbo_splits: 25
  pbo_min_symbols: 4
  stagnation:
    enabled: true
    window: 8
    min_pval_delta: 0.02
    mutation_bump: 0.15
  debug_relaxed_gates: false
  fitness_weights:
    profit_signal: 0.7
    trade_signal: 0.3
    complexity_penalty: 0.015  # TEMP: discourage churny formulas; restore 0.001–0.005
  prefilter:
    enabled: true
    sign_p_max: 0.15         # BOOTSTRAP: stricter sign gate to reduce weak candidates
    median_bps_min: 0.8      # BOOTSTRAP: slightly higher effect-size floor
  novelty:
    enabled: true
    max_per_family: 1        # Keep only the top candidate per feature-family per generation
    include_depth: true      # Include formula depth in family key

prober:
  enabled: true
  perturbations: 24
  delta_fraction: 0.15
  min_robust_score: 0.55
  mdd_escalation_multiplier: 1.50  # Relaxed from hardcoded 1.25 (adaptive knob)

# --- Lane Configuration ---
lanes:
  # Smoothing factor for lane weight adjustments (0=no change, 1=instant).
  smoothing_factor: 0.1
  
  # Max single-step change in lane weight.
  max_step_change: 0.05
  
  # Initial lane weights. Must sum to 1.0.
  initial_weights:
    base: 0.0       # Reserved for future use
    core: 0.05      # START LOW: No proven alphas exist yet.
    moonshot: 0.95  # START HIGH: Focus capital on discovery and experimentation.
  
  # Per-lane configuration overrides.
  overrides:
    moonshot:
      kelly_fraction: 0.25  # More conservative for experimental strategies
    core:
      kelly_fraction: 0.50  # Standard Kelly for proven strategies

ensemble:
  enabled: true
  min_alphas_for_ensemble: 3
  max_alphas_in_ensemble: 10
  weighting_scheme: "inverse_variance"

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

# --- Risk Management ---
risk:
  # Kill switch: stop all trading if equity drops below this % of initial capital.
  equity_floor_pct: 0.80  # Preserve 80% of capital minimum
  
  # Daily stop: flatten all positions if equity drops by this % in a 24h period.
  daily_stop_pct: 0.05  # Max 5% daily loss (institutional standard)
  
  # Max % of portfolio equity allowed in a single symbol.
  max_symbol_weight: 0.25  # Reduce concentration risk from 0.35
  
  # Max gross exposure (% of portfolio equity).
  max_gross_weight: 0.95  # Slight reduction from 1.0 for safety buffer
  max_order_notional_usd: 150
  max_consecutive_errors: 8
  phases:
    "1000":   { kelly_fraction: 0.6, max_order_notional_usd: 500 }
    "10000":  { kelly_fraction: 0.7, max_order_notional_usd: 1000 }
    "100000": { kelly_fraction: 0.8, max_order_notional_usd: 5000 }
  conserve_mode:
    dd_trigger_pct: 0.15
    gross_weight_scalar: 0.5
    kelly_scalar: 0.6

# --- Execution ---
execution:
  mode: "paper"
  primary_exchange: "coinbase"
  trade_universe_source: "screener"
  paper_fees_bps: 3     # TEMP: lower cost to surface early edge
  paper_slippage_bps: 3 # TEMP: lower cost to surface early edge
  max_order_notional_usd: 150

llm:
  provider: "openai"
  enabled: true
  proposer_enabled: true
  model: "gpt-4o-mini"
  temperature: 0.6                # TEMP: increase variety to escape local minima
  max_tokens: 400
  max_suggestions_per_cycle: 10   # BOOTSTRAP: lower to reduce trial count added to population
  threshold_min: 0.5
  threshold_max: 0.9
  adaptive_temp:
    enabled: true
    rejection_window: 50
    rejection_threshold: 0.5
    temp_increment: 0.05
    temp_max: 1.0
  feature_suppression:
    enabled: true
    min_sharpe_for_inclusion: 0.5
    min_trades_for_inclusion: 20
    lookback_cycles: 10
  json_harden:
    enabled: true
    max_retries: 3
    retry_delay_seconds: 1
  telemetry:
    log_prompts: true
    log_tokens: true
    log_latency: true
  guardrails:
    max_prompt_tokens: 4096
    max_completion_tokens: 1024
    concentration_threshold_single: 0.5
    concentration_threshold_total: 0.9
    variance_threshold_min: 0.001
    variance_threshold_max: 100.0

eil:
  enabled: true
  fast_window_days: 150  # BOOTSTRAP: widen to increase trade counts for CV power
  max_parallel_jobs: 8
  max_queue: 5000
  survivor_top_k: 25
  scan_batch_size: 200
  # max_cycles: 10 # Set to 0 or remove for continuous running # TEMP: for short EIL runs
  max_cycles: 1000000  # 0 means run indefinitely
  timeframe_preference: ["1h"]  # TEMP: bias to higher TF to reduce churn/cost drag

adaptive:
  enabled: true
  stop_vol_window_bars: 24
  daily_stop_pct_floor: 0.05
  daily_stop_pct_ceiling: 0.20
  stop_vol_multiplier: 6.0
  screener_max_markets_min: 24
  screener_max_markets_max: 72
  population_size_min: 240
  population_size_max: 800

registry:
  allowed_quotes_global: ["USD","USDT","USDC","DAI","FDUSD","TUSD","PYUSD","EUR","GBP"]
  allowed_quotes_by_venue:
    kraken: ["USD","USDT","USDC","EUR"]
    coinbase: ["USD","USDC"]
  base_aliases:
    BTC: ["XBT"]
    IOTA: ["MIOTA"]
  cache_ttl_s: 600
  catalog_refresh_seconds: 900
  timeframe_aliases_by_venue:
    coinbase:
      "6h": "6h"
    kraken:
      "6h": "4h"
