system:
  loop_interval_seconds: 30
  log_level: "INFO"
  redis_host: "localhost"
  redis_port: 6379
  seed: 1337

features:
  zscore_lookback: 200   # NEW: rolling window for lagged z-score normalization

data_source:
  exchanges: ["coinbase", "kraken"]

# v4.7.5 data-plane
harvester:
  core_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","AVAX_USD_SPOT","LINK_USD_SPOT",
                 "ADA_USD_SPOT","XRP_USD_SPOT","DOGE_USD_SPOT","MATIC_USD_SPOT","DOT_USD_SPOT",
                 "LTC_USD_SPOT","LDO_USD_SPOT","BCH_USD_SPOT","UNI_USD_SPOT","ATOM_USD_SPOT","FIL_USD_SPOT",
                 "NEAR_USD_SPOT","ARB_USD_SPOT","OP_USD_SPOT","INJ_USD_SPOT","APT_USD_SPOT","XLM_USD_SPOT",
                 "ALGO_USD_SPOT","SUI_USD_SPOT","SHIB_USD_SPOT"]
  dynamic_enabled: true
  timeframes_by_lane:
    core:     ["1m","5m","15m","1h","4h","1d"]
    moonshot: ["1m","5m","15m"]
    eil:      "on_demand"
  quotas:
    coinbase: { max_requests_per_min: 45, min_sleep_ms: 220 }
    kraken:   { max_requests_per_min: 45, min_sleep_ms: 250 }
  # NEW: per-venue gap tolerances + timeframe fallback
  gap_accept_overrides:
    coinbase: { "1m": 0.60, "5m": 0.45 }
  tf_fallback:
    coinbase: { "1m": "5m" }
  per_exchange_bootstrap:
    coinbase: { "1h": 365, "4h": 730 }  # UPDATED: deeper initial history for hourly & aliased 4h (6h) on coinbase
    kraken:   { "1h": 365, "4h": 730 }
  bootstrap_days_default:
    "1m": 7
    "5m": 14
    "15m": 30
    "1h": 365
    "4h": 730
    "1d": 1825
  retention_days:
    "1m": 90
    "5m": 90
    "15m": 365
    "1h": 1825
    "4h": 1825
    "1d": 3650
  max_gap_pct_accept: 0.30
  bootstrap_days_override: {"1m": 7, "5m": 14, "15m": 30 }
  staged_backfill:
    enabled: true  # ENABLED (was false) deeper phased intraday history seeding
    targets_days:
      "1m":  [7, 30, 90]      # UPDATED deeper progression
      "5m":  [30, 180, 365]   # UPDATED deeper progression
      "15m": [90, 365, 730]   # UPDATED deeper progression
  availability:
    miss_threshold: 3
    suppress_ttl_minutes: 360
  aggregate_timeframes:
    enabled: true
    from: "5m"
    to: ["1h"]
    min_native_rows_threshold: 50
    max_tail_hours: 72
  merged_loader:
    enabled: false
    primary_depth_exchange: "kraken"
    tail_exchange: "coinbase"
    tail_replace_bars: 3
  bootstrap_mode: "parallel"         # NEW: parallel bootstrap worker (deep history) vs inline
  min_coverage_for_research: 0.30     # NEW: initial coverage ratio gate for research timeframe
  high_coverage_threshold: 0.80       # NEW: target after first promotion
  priority_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT"]  # NEW: tier A ordering
  partial_harvest: false              # TEMP: full-cycle bootstrap; revert to true after coverage

screener:
  snapshot_dir: "data/screener_snapshots"
  min_24h_volume_usd: 10000000
  min_price: 0.20
  max_markets: 100
  typical_order_usd: 200
  max_spread_bps: 25
  max_impact_bps: 60
  stablecoin_parity_warn_bps: 100
  derivatives_enabled: false
  sentiment_weight: 0.0
  exclude_stable_stable: true  # NEW: skip stablecoin <-> stablecoin pairs

feeds:
  cryptopanic: { enabled: true }
  onchain:     { enabled: false, min_notional_eth: 100.0 }  # disabled by default: placeholder returns 0.0 without API key
  orderflow:   { enabled: true, top_levels: 5 }

validation:
  dsr:
    enabled: true  # TEMP bootstrap: disabled to allow faster initial promotions; revert to true after seeding
    min_prob: 0.60       # require >=60% probability Sharpe not luck (deflated)
    benchmark_sr: 0.0

discovery:
  population_size: 320              # bumped 160→320
  generations_per_cycle: 3          # bumped 2→3
  panel_symbols: 5
  cv_folds: 4
  cv_embargo_bars: 2
  fdr_alpha: 0.10
  cv_method: "kfold"
  auto_cpcv: true                   # NEW: switch to CPCV when panel symbols ≥8 or population large
  max_promotions_per_cycle: 3
  max_promotions_per_day: 12
  promotion_buffer_multiplier: 1.0
  enable_pruning: true
  defer_until_coverage: true          # NEW: gate research until minimal symbol coverage satisfied
  min_panel_symbols: 3                # NEW: required symbols meeting coverage/bars thresholds
  min_bars_per_symbol: 100            # NEW: bars required on research timeframe per symbol before inclusion
  promotion_criteria:
    min_trades: 75
    min_sortino: 1.25
    max_mdd: 0.20
    min_sharpe: 1.10
    min_win_rate: 0.52
  factor_correlation_max: 0.80
  enforce_current_gates_on_start: false   # NEW: retroactive gate enforcement for legacy alphas
  max_return_padding_trim: 5              # NEW: max trailing zero returns to trim per hygiene pass
  max_population_size: 1000               # NEW: cap genetic population to bound memory

prober:
  enabled: true
  perturbations: 64
  delta_fraction: 0.15
  min_robust_score: 0.55

lanes:
  core:     { base_fraction: 0.95, min_fraction: 0.85, max_fraction: 0.99 }
  moonshot: { base_fraction: 0.05, min_fraction: 0.01, max_fraction: 0.20 }
  smoothing_alpha: 0.30      # NEW: EWMA smoothing for lane performance
  dead_band: 0.10            # NEW: performance diff within +/- dead_band → no shift
  max_step_per_cycle: 0.02   # NEW: max absolute moonshot fraction change per cycle
  probation:                 # NEW: initial cap for fresh moonshot promotions
    trades_min: 50
    weight_cap: 0.03
  retag:                     # NEW: moonshot→core promotion criteria (A)
    enabled: true
    min_trades: 300
    min_sharpe: 1.00
    min_sortino: 1.20
    max_mdd: 0.25

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

risk:
  daily_stop_pct: 0.10
  equity_floor_pct: 0.50
  max_symbol_weight: 0.35
  max_gross_weight: 1.00
  max_order_notional_usd: 150
  max_consecutive_errors: 3
  phases:
    "1000":   { kelly_fraction: 0.6, max_order_notional_usd: 500 }
    "10000":  { kelly_fraction: 0.7, max_order_notional_usd: 1000 }
    "100000": { kelly_fraction: 0.8, max_order_notional_usd: 5000 }
  conserve_mode:
    dd_trigger_pct: 0.15
    gross_weight_scalar: 0.5
    kelly_scalar: 0.6

execution:
  primary_exchange: "coinbase"
  mode: "paper"
  paper_fees_bps: 18
  paper_slippage_bps: 5

llm:
  provider: "openai"
  enable: true
  max_suggestions_per_cycle: 3
  threshold_min: -5.0   # NEW: clamp LLM numeric thresholds lower bound
  threshold_max: 5.0    # NEW: clamp LLM numeric thresholds upper bound

eil:
  enabled: true
  fast_window_days: 45
  max_parallel_jobs: 8
  max_queue: 5000
  survivor_top_k: 25
  scan_batch_size: 200   # NEW: Redis SCAN batch size for EIL candidates

adaptive:
  enabled: true
  stop_vol_window_bars: 24
  daily_stop_pct_floor: 0.05
  daily_stop_pct_ceiling: 0.20
  screener_max_markets_min: 12
  screener_max_markets_max: 36
  population_size_min: 120
  population_size_max: 400          # bumped ceiling 240→400

registry:
  allowed_quotes_global: ["USD","USDT","USDC","DAI","FDUSD","TUSD","PYUSD","EUR","GBP"]
  allowed_quotes_by_venue:
    kraken: ["USD","USDT","USDC","EUR"]
    coinbase: ["USD","USDC"]
  base_aliases:
    BTC: ["XBT"]
    IOTA: ["MIOTA"]
  cache_ttl_s: 600
  catalog_refresh_seconds: 900
  timeframe_aliases_by_venue:
    coinbase:
      "6h": "6h"
    kraken:
      "6h": "4h"
