system:
  loop_interval_seconds: 30
  log_level: "INFO"
  redis_host: "localhost"
  redis_port: 6379
  seed: 1337

features:
  zscore_lookback: 200   # NEW: rolling window for lagged z-score normalization

data_source:
  exchanges: ["coinbase", "kraken"]

# v4.7.5 data-plane
harvester:
  core_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","LTC_USD_SPOT","UNI_USD_SPOT","ATOM_USD_SPOT"]
  restrict_single_symbol: false
  dynamic_enabled: false
  timeframes_by_lane:
    core: ["1m","5m","1h"]
    moonshot: ["1m","5m"]
    eil: "on_demand"
  partial_harvest: true          # PHASE1: re-enable for cadence
  aggregate_timeframes:
    enabled: true                # PHASE1: restore synthetic aggregation
  checkpoint_reconcile:
    enabled: true                # PHASE1: restore forward reconcile
  bootstrap_mode: "inline"
  min_coverage_for_research: 0.30     # NEW: initial coverage ratio gate for research timeframe
  high_coverage_threshold: 0.80       # NEW: target after first promotion
  priority_symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT"]  # NEW: tier A ordering
  panel_target_days: { "1m": 7, "5m": 14, "15m": 30, "1h": 30 }  # NEW: dynamic panel targets (days) for gate derivation
  bootstrap_days_default: { "1m": 2, "5m": 7, "15m": 14, "1h": 45, "4h": 120, "1d": 365 }  # NEW: default historical depth per timeframe (days) used when no checkpoint; aligns with staged_backfill & avoids KeyError
  # NOTE: values are config knobs (no magic); adjust to trade off initial IO vs statistical power.
  # per_exchange_bootstrap optional override structure: { exchange: { timeframe: days } }

screener:
  snapshot_dir: "data/screener_snapshots"
  min_24h_volume_usd: 10000000
  min_price: 0.20
  max_markets: 100
  typical_order_usd: 200
  max_spread_bps: 25
  max_impact_bps: 60
  stablecoin_parity_warn_bps: 100
  derivatives_enabled: false
  sentiment_weight: 0.0
  exclude_stable_stable: true  # NEW: skip stablecoin <-> stablecoin pairs

feeds:
  cryptopanic: { enabled: true }
  onchain:     { enabled: false, min_notional_eth: 100.0 }  # disabled by default: placeholder returns 0.0 without API key
  orderflow:   { enabled: true, top_levels: 5 }

validation:
  dsr:
    enabled: true
    min_prob: 0.50
    benchmark_sr: 0.0
  sparse_trades:
    enabled: true
    winrate_p_threshold_trades: 25

discovery:
  population_size: 320
  generations_per_cycle: 3
  panel_symbols: 5
  cv_folds: 4
  cv_embargo_bars: 2
  fdr_alpha: 0.20
  cv_method: "kfold"
  auto_cpcv: true
  max_promotions_per_cycle: 1        # PHASE1: allow limited promotions
  max_promotions_per_day: 3          # PHASE1: limited daily promotions
  promotion_buffer_multiplier: 1.0
  enable_pruning: true
  defer_until_coverage: true
  min_panel_symbols: 3
  min_bars_per_symbol: 100
  promotion_criteria:
    min_trades: 40                  # PHASE1: step up from 30
    min_sortino: 0.60               # PHASE1 tightened
    max_mdd: 0.30
    min_sharpe: 0.50                # PHASE1 tightened
    min_win_rate: 0.48              # PHASE1 tightened
  factor_correlation_max: 0.80
  enforce_current_gates_on_start: false
  max_return_padding_trim: 5
  max_population_size: 1000
  feature_min_non_nan_ratio: 0.30
  feature_min_variance: 1e-06
  reseed_fraction: 0.30
  fitness_drawdown_penalty_scale: 0.40
  rejection_sample_size: 8
  rejection_alert_ratio: 0.70
  fitness_concentration_penalty_scale: 0.25
  fitness_variance_penalty_scale: 0.15
  fitness_activation_scale: 20
  fitness_activation_weight: 0.5     # NEW: weight for activation_gain modulation
  max_formula_depth: 3               # NEW: enable deeper boolean trees
  depth3_prob: 0.25                  # NEW: probability of sampling depth 3 formulas
  adaptive:
    enabled: true
    continuity_threshold: 0.80
    variance_threshold: 0.10
    continuity_suppression_patience: 5
    tuning_enabled: true
    rejection_pval_high_ratio: 0.75
    population_step: 40
  debug_relaxed_gates: false         # PHASE1: disable FDR bypass
  fitness_weights:
    profit_signal: 0.7
    trade_signal: 0.3

prober:
  enabled: true
  perturbations: 64
  delta_fraction: 0.15
  min_robust_score: 0.55

lanes:
  core:     { base_fraction: 0.95, min_fraction: 0.85, max_fraction: 0.99 }
  moonshot: { base_fraction: 0.05, min_fraction: 0.01, max_fraction: 0.20 }
  smoothing_alpha: 0.30      # NEW: EWMA smoothing for lane performance
  dead_band: 0.10            # NEW: performance diff within +/- dead_band → no shift
  max_step_per_cycle: 0.02   # NEW: max absolute moonshot fraction change per cycle
  probation:                 # NEW: initial cap for fresh moonshot promotions
    trades_min: 50
    weight_cap: 0.03
  retag:                     # NEW: moonshot→core promotion criteria (A)
    enabled: true
    min_trades: 300
    min_sharpe: 1.00
    min_sortino: 1.20
    max_mdd: 0.25

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

risk:
  daily_stop_pct: 0.10
  equity_floor_pct: 0.50
  max_symbol_weight: 0.35
  max_gross_weight: 1.00
  max_order_notional_usd: 150
  max_consecutive_errors: 8     # PHASE1: step down from 12
  phases:
    "1000":   { kelly_fraction: 0.6, max_order_notional_usd: 500 }
    "10000":  { kelly_fraction: 0.7, max_order_notional_usd: 1000 }
    "100000": { kelly_fraction: 0.8, max_order_notional_usd: 5000 }
  conserve_mode:
    dd_trigger_pct: 0.15
    gross_weight_scalar: 0.5
    kelly_scalar: 0.6

execution:
  primary_exchange: "coinbase"
  mode: "paper"
  paper_fees_bps: 18
  paper_slippage_bps: 5
  max_holding_bars: 24   # NEW: forced exit horizon to boost trade sample entropy

llm:
  provider: "openai"
  enable: false   # SANDBOX: disable LLM proposer until loop stable
  max_suggestions_per_cycle: 3
  threshold_min: -5.0   # NEW: clamp LLM numeric thresholds lower bound
  threshold_max: 5.0    # NEW: clamp LLM numeric thresholds upper bound

eil:
  enabled: true
  fast_window_days: 75  # CHANGED: extended from 45→75 to increase statistical power (see migration-notes 2025-08-22)
  max_parallel_jobs: 8
  max_queue: 5000
  survivor_top_k: 25
  scan_batch_size: 200   # NEW: Redis SCAN batch size for EIL candidates

adaptive:
  enabled: true
  stop_vol_window_bars: 24
  daily_stop_pct_floor: 0.05
  daily_stop_pct_ceiling: 0.20
  stop_vol_multiplier: 6.0
  screener_max_markets_min: 12
  screener_max_markets_max: 36
  population_size_min: 120
  population_size_max: 400          # bumped ceiling 240→400

registry:
  allowed_quotes_global: ["USD","USDT","USDC","DAI","FDUSD","TUSD","PYUSD","EUR","GBP"]
  allowed_quotes_by_venue:
    kraken: ["USD","USDT","USDC","EUR"]
    coinbase: ["USD","USDC"]
  base_aliases:
    BTC: ["XBT"]
    IOTA: ["MIOTA"]
  cache_ttl_s: 600
  catalog_refresh_seconds: 900
  timeframe_aliases_by_venue:
    coinbase:
      "6h": "6h"
    kraken:
      "6h": "4h"
