# Back-compat mapping; registry is source of truth now.
BTC_USD_SPOT:  {coinbase: "BTC/USD",  kraken: "XBT/USD"}
ETH_USD_SPOT:  {coinbase: "ETH/USD",  kraken: "ETH/USD"}
SOL_USD_SPOT:  {coinbase: "SOL/USD",  kraken: "SOL/USD"}
AVAX_USD_SPOT: {coinbase: "AVAX/USD", kraken: "AVAX/USD"}
LINK_USD_SPOT: {coinbase: "LINK/USD", kraken: "LINK/USD"}
ADA_USD_SPOT:  {coinbase: "ADA/USD",  kraken: "ADA/USD"}
XRP_USD_SPOT:  {coinbase: "XRP/USD",  kraken: "XRP/USD"}
DOGE_USD_SPOT: {coinbase: "DOGE/USD", kraken: "DOGE/USD"}
MATIC_USD_SPOT:{coinbase: "MATIC/USD",kraken: "MATIC/USD"}
DOT_USD_SPOT:  {coinbase: "DOT/USD",  kraken: "DOT/USD"}
